lab6 - CI/CD (test commit)

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -15,9 +15,9 @@ jobs:
     steps:
       - name: Check 2
         run: |
-          ping -c 4 172.25.52.197
-          ping -c 4 172.17.0.2
-          ping -c 8.8.8.8
+          ping -c 4 172.25.52.197 || echo "failed"
+          ping -c 4 172.17.0.2 || echo "failed"
+          ping -c 8.8.8.8 || echo "failed"
 
       - name: Check 2
         run: |
